name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Demo
    container: swift:latest
    steps:
    - uses: actions/checkout@v4
    - run: ls -la ~/.swiftpm/swift-sdks
    - run: ./setup.sh
    - run: ./build-swift.sh
