name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'
    - run: swift build
