name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v4
    - run: cd Demo
    - run: ./setup.sh
    - run: ./build-swift.sh
